[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=railway $JAVA_OPTS -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.env]
JAVA_OPTS = "-Xmx512m -Xms256m" 