INSERT INTO GAME (title, description, image_url, game_url, category) VALUES
('Minecraft Classic', 'Juego de construcción y aventura', 'https://i.imgur.com/8zY7HoD.jpg', 'https://classic.minecraft.net/', 'adventure'),
('Doom', 'Clásico juego de disparos en primera persona', 'https://i.imgur.com/yqHoJjF.jpg', 'https://dos.zone/doom/', 'action'),
('Super Mario 64', 'Clásico juego de plataformas 3D', 'https://i.imgur.com/4l8Qyvi.jpg', 'https://sm64.io/', 'adventure'),
('Pokemon Red', 'RPG clásico de Nintendo', 'https://i.imgur.com/rKO0nRh.jpg', 'https://pokemon-red.io/', 'adventure'),
('Sonic the Hedgehog', 'Plataformas de alta velocidad', 'https://i.imgur.com/7DJw1wT.jpg', 'https://sonic.sega.com/play/', 'arcade'),
('Pac-Man', 'El clásico come-fantasmas', 'https://i.imgur.com/8OZJ3GI.png', 'https://www.google.com/logos/2010/pacman10-i.html', 'arcade'),
('Space Invaders', 'Arcade clásico de disparos', 'https://i.imgur.com/7M0uMwO.png', 'https://spaceinvaders.io/', 'arcade'),
('Tetris', 'El juego de bloques más famoso', 'https://i.imgur.com/K4JxZ8r.jpg', 'https://tetris.com/play-tetris', 'puzzle'),
('Street Fighter II', 'Legendario juego de lucha', 'https://i.imgur.com/QxZ9WxD.jpg', 'https://www.retrogames.cc/arcade-games/street-fighter-ii.html', 'action'),
('The Legend of Zelda', 'Aventura clásica de acción', 'https://i.imgur.com/YtZVm0H.jpg', 'https://www.retrogames.cc/nes-games/legend-of-zelda.html', 'adventure'),
('2048', 'Adictivo juego de puzzle numérico', 'https://i.imgur.com/ohPFPcZ.png', 'https://play2048.co/', 'puzzle'),
('Flappy Bird', 'El famoso juego del pájaro', 'https://i.imgur.com/706nxRR.png', 'https://flappybird.io/', 'arcade'),
('Snake', 'El clásico juego de la serpiente', 'https://i.imgur.com/8SJM8Qh.png', 'https://playsnake.org/', 'arcade'),
('Chess', 'El juego de estrategia por excelencia', 'https://i.imgur.com/9pHd46r.png', 'https://www.chess.com/play/online', 'strategy'),
('Sudoku', 'Clásico juego de lógica numérica', 'https://i.imgur.com/xJVKWhK.png', 'https://sudoku.com/', 'puzzle'),
('Minesweeper', 'El clásico buscaminas', 'https://i.imgur.com/LXHwwgj.png', 'https://minesweeper.online/', 'puzzle'),
('Solitaire', 'El juego de cartas más popular', 'https://i.imgur.com/YZ4il9N.png', 'https://www.solitr.com/', 'cards'),
('Wordle', 'Adivina la palabra del día', 'https://i.imgur.com/2TRX3Fy.png', 'https://www.nytimes.com/games/wordle/index.html', 'puzzle'),
('Crossy Road', 'Versión moderna de Frogger', 'https://i.imgur.com/UhP9XZF.jpg', 'https://poki.com/en/g/crossy-road', 'arcade'),
('Cut the Rope', 'Alimenta al monstruo cortando cuerdas', 'https://i.imgur.com/XWU8eMD.png', 'https://www.crazygames.com/game/cut-the-rope', 'puzzle');