INSERT INTO GAME (title, description, image_url, game_url, category) VALUES
('Minecraft Classic', 'Juego de construcción y aventura', '/images/games/descarga.webp', 'https://classic.minecraft.net/', 'adventure'),
('Doom', 'Clásico juego de disparos en primera persona', '/images/games/Doom.webp', 'https://dos.zone/doom/', 'action'),
('Super Mario 64', 'Clásico juego de plataformas 3D', '/images/games/mario.jpg', 'https://sm64.io/', 'adventure'),
('Pokemon Red', 'RPG clásico de Nintendo', '/images/games/pokemon.jpg', 'https://pokemon-red.io/', 'adventure'),
('Sonic the Hedgehog', 'Plataformas de alta velocidad', '/images/games/sonic.jpg', 'https://playclassic.games/games/jump-and-run-genesis-games-online/play-sonic-the-hedgehog-online/', 'arcade'),
('Pac-Man', 'El clásico come-fantasmas', '/images/games/pacman.webp', 'https://www.google.com/logos/2010/pacman10-i.html', 'arcade'),
('Space Invaders', 'Arcade clásico de disparos', '/images/games/space-invaders.jpg', 'https://spaceinvaders.io/', 'arcade'),
('Tetris', 'El juego de bloques más famoso', '/images/games/tetris.jpg', 'https://www.goodoldtetris.com/', 'puzzle'),
('Street Fighter II', 'Legendario juego de lucha', '/images/games/street-figther.jpg', 'https://www.retrogames.cc/arcade-games/street-fighter-ii.html', 'action'),
('The Legend of Zelda', 'Aventura clásica de acción', '/images/games/zelda.jpg', 'https://www.retrogames.cc/nes-games/legend-of-zelda.html', 'adventure'),
('2048', 'Adictivo juego de puzzle numérico', '/images/games/2048.jpg', 'https://play2048.co/', 'puzzle'),
('Flappy Bird', 'El famoso juego del pájaro', '/images/games/flappybird.jpg', 'https://flappybird.io/', 'arcade'),
('Snake', 'El clásico juego de la serpiente', '/images/games/snake.jpg', 'https://playsnake.org/', 'arcade'),
('Chess', 'El juego de estrategia por excelencia', '/images/games/chess.png', 'https://www.chess.com/live', 'strategy'),
('Sudoku', 'Clásico juego de lógica numérica', '/images/games/sudoku.jpg', 'https://sudoku.com/', 'puzzle'),
('Minesweeper', 'El clásico buscaminas', '/images/games/mine.jpg', 'https://minesweeper.online/', 'puzzle'),
('Solitaire', 'El juego de cartas más popular', '/images/games/soliotaire.png', 'https://www.solitr.com/', 'cards'),
('Wordle', 'Adivina la palabra del día', '/images/games/wordle.png', 'https://www.nytimes.com/games/wordle/index.html', 'puzzle'),
('Crossy Road', 'Versión moderna de Frogger', '/images/games/crossyroad.jpg', 'https://poki.com/en/g/crossy-road', 'arcade'),
('Cut the Rope', 'Alimenta al monstruo cortando cuerdas', '/images/games/cutherope.jpg', 'https://www.crazygames.com/game/cut-the-rope', 'puzzle');